version: "3.8"
services:
    postgresql:
        image: postgres    
        env_file: 
            - dev.env 
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432
        container_name: postgresql
    adminer:
        image: adminer
        ports:
            - 8080:8080