version: "3.7"
services:
  talker:
    build:
      network: host
      context: ../chatbot_ru/talker
    env_file: 
      - dev.env 
    ports:
      - 8000:8000                  
    container_name: talker
  telegram:
    build:
      network: host
      context: ../chatbot_ru/talker/telegram
    env_file: 
      - dev.env
    depends_on: 
      - talker           
    container_name: telegram