version: "3.7"
services:
  talker:
    build:
      context: ../chatbot_ru/talker
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    env_file: 
      - dev.env 
    ports:
      - 8000:8000                 
    container_name: talker
  telegram:
    build:
      context: ../chatbot_ru/talker/telegram
    env_file: 
      - dev.env
    depends_on: 
      - talker           
    container_name: telegram
  nginx:
    container_name: nginx
    build:
      context: ../chatbot_ru/talker/talker_nginx
    env_file: 
      - dev.env
    ports:
      - 7999:7999
    depends_on:
      - talker