version: "3.7"
services:
  talker:
    build:
      network: host
      context: ../chatbot_ru/talker
    volumes:
        - type: bind
          source: c:/Users/evgeniic/py_envs/pikabu_bot/chatbot_ru/models
          target: /talker/models
    env_file: 
      - C:\Users\evgeniic\py_envs\pikabu_bot\chatbot_ru\dev.env            
    container_name: talker
    tty: true