version: "3.7"
services:
  talker:
    build:
      network: host
      context: ../chatbot_ru/talker
    volumes:
        - type: bind
          source: path_to_models
          target: /talker/models
    env_file: 
      - dev.env            
    container_name: talker
    tty: true